Fix 'Cannot find module ‘puppeteer/DeviceDescriptors’' error
If you are using puppeteer version >= 5.0 you would get following error:

`Error: Cannot find module ‘puppeteer/DeviceDescriptors’`

I adjusted the line causing the error.

btw. Thanks for this cool project, I'm using it instead of EyeWitness 👍